import {test,expect} from '@playwright/test';
import {createHandleState} from '../src/machining/WorkpieceState.js';
import {CampaignStore} from '../src/levels/CampaignStore.js';
test('campaign demo pause/replay/skip isolates player geometry and reload keeps the checkpoint',async({page})=>{
  test.setTimeout(300000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/#/campaign/handle');
  const start=page.getByRole('button',{name:'開始實作',exact:true});
  await expect(start).toBeEnabled({timeout:60000});await start.click();
  await expect(page.getByTestId('cut-length')).toHaveText('300.000');
  const saved=await page.evaluate(()=>localStorage.getItem('machine-lab.campaign.handle.v1'));
  await page.getByRole('button',{name:'看任務／示範',exact:true}).click();
  await page.getByRole('button',{name:'觀看示範',exact:true}).click();
  await expect(page.getByTestId('demo-status')).toContainText('playing',{timeout:30000});
  await page.getByRole('button',{name:'暫停示範',exact:true}).click();
  await expect(page.getByTestId('demo-status')).toContainText('paused');
  await expect(page.locator('button',{hasText:'X 歸零'})).toBeDisabled();
  expect(await page.evaluate(()=>localStorage.getItem('machine-lab.campaign.handle.v1'))).toBe(saved);
  await page.getByRole('button',{name:'重新播放',exact:true}).click();
  await expect(page.getByTestId('demo-status')).toContainText('playing',{timeout:30000});
  await page.getByRole('button',{name:'跳過示範／返回操作',exact:true}).click();
  await expect(page.getByTestId('demo-status')).toContainText('finished',{timeout:30000});
  await expect(page.getByTestId('cut-length')).toHaveText('300.000');
  expect(await page.evaluate(()=>localStorage.getItem('machine-lab.campaign.handle.v1'))).toBe(saved);
  await page.reload();await expect(start).toBeEnabled({timeout:60000});await start.click();
  await expect(page.getByTestId('cut-length')).toHaveText('300.000');
  expect(errors).toEqual([]);
});

test('player X/Z feed cuts a taper and chamfer through the UI, reaches draft finish without fake acceptance',async({page})=>{
  test.setTimeout(900000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  // Stage-entry fixture only; all taper/chamfer geometry below is produced by player UI commands.
  const stock=createHandleState();stock.lengthMm=240;stock.profile.radiusMm.length=480;
  const data=new CampaignStore().fresh();data.currentLevel=1;data.completedLevels=['handle-basic'];
  data.revisions.push({revision:1,levelId:'handle-basic',state:stock,measurements:{status:'draft'}});data.working=stock;
  await page.goto('/#/levels');
  await page.evaluate(save=>localStorage.setItem('machine-lab.campaign.handle.v1',JSON.stringify(save)),data);
  await page.getByRole('region',{name:'槌柄路線'}).getByRole('link',{name:'繼續 →'}).click();
  const start=page.getByRole('button',{name:'開始實作',exact:true});
  await expect(start).toBeEnabled({timeout:60000});await start.click();
  await page.getByText('移動到工件座標',{exact:true}).click();
  const move=async(a,v)=>{await page.getByRole('spinbutton',{name:a+' 工件座標目標 (mm)'}).fill(String(v));await page.getByRole('button',{name:'移動 '+a,exact:true}).click();};
  const setup=async()=>{
    await move('X',24);await move('Z',100);await page.getByRole('button',{name:'▶ 啟動主軸'}).click();
    await move('X',20);await page.getByRole('button',{name:'X 歸零',exact:true}).click();
    await move('X',4);await move('Z',241);await move('X',0);await move('Z',240);
    await page.getByRole('button',{name:'Z 歸零',exact:true}).click();await expect(page.getByTestId('level-step')).toContainText('Step 8');
  };
  const line=async(x,z)=>{await page.getByRole('spinbutton',{name:'聯動 X',exact:true}).fill(String(x));await page.getByRole('spinbutton',{name:'聯動 Z',exact:true}).fill(String(z));await page.getByRole('button',{name:'X/Z 聯動進給',exact:true}).click();};
  const finish=async()=>{await page.getByRole('button',{name:'■ 停止主軸'}).click();await expect(page.getByTestId('level-step')).toContainText('Step 10');
    await page.getByRole('button',{name:'檢查加工結果',exact:true}).click();await page.getByRole('button',{name:'保存實際工件 → 下一關',exact:true}).click();};
  await setup();await move('X',4);await move('Z',-120);await move('X',-3.7);await line(-10.7,-20);
  await expect(page.getByTestId('level-step')).toContainText('Step 9');await finish();
  await expect(page.getByTestId('campaign-save')).toContainText('第 3 關');
  const taper=await page.evaluate(()=>JSON.parse(localStorage.getItem('machine-lab.campaign.handle.v1')).revisions[2].state);
  expect(taper.profile.radiusMm[439]).toBeCloseTo(4.65,6);expect(taper.profile.radiusMm[240]).toBeLessThan(8.15);
  await start.click();await setup();await move('X',4);await move('Z',-1);await move('X',0);await line(-2,0);await finish();
  await expect(page.getByTestId('campaign-save')).toContainText('第 4 關');
  await expect(page.getByText('製程待確認：壓花／螺紋尚未加工，不能判定成功。可保留存檔，待補圖面資料。',{exact:true})).toBeVisible();
  await start.click();await page.getByRole('button',{name:'檢查加工結果',exact:true}).click();
  await expect(page.getByTestId('level-result')).toContainText('待老師確認');
  await expect(page.getByRole('button',{name:'保存實際工件 → 下一關',exact:true})).toHaveCount(0);
  const final=await page.evaluate(()=>JSON.parse(localStorage.getItem('machine-lab.campaign.handle.v1')).working);
  expect(final.profile.radiusMm.at(-1)).toBe(9);expect(final.features).toEqual([]);expect(errors).toEqual([]);
});
