import {test, expect} from '@playwright/test';

test('hammer lesson: demo isolation, zeroing, dwell, retry, inheritance and reload', async ({page}) => {
 const errors=[]; page.on('pageerror', e => errors.push(e.message));
 await page.goto('/#/levels');
 await page.locator('.lesson-card').first().getByRole('link', {name:'開始體驗 →'}).click();
 const start=page.getByRole('button',{name:'啟動主軸與進給'});
 await expect(start).toBeDisabled();
 await page.getByRole('button',{name:'觀看本關示範'}).click();
 await expect.poll(async()=>parseFloat(await page.getByTestId('tool-position').textContent())).toBeLessThan(109);
 await page.getByRole('button',{name:'返回練習'}).click();
 await expect(page.getByTestId('tool-position')).toHaveText('110.00 mm');
 await expect(page.getByTestId('travel')).toHaveText('尚未歸零');
 await page.getByRole('button',{name:'座標歸零'}).click();
 await expect(page.getByTestId('tool-position')).toHaveText('110.00 mm');
 await expect(page.getByTestId('travel')).toHaveText('0.00 mm');
 await start.click();
 await expect.poll(async()=>parseFloat(await page.getByTestId('tool-position').textContent())).toBeLessThan(108);
 await page.getByRole('button',{name:'停止進給（主軸續轉）',exact:true}).click();
 await expect(page.getByTestId('marks-count')).toHaveText('停留刀痕：1 處', {timeout:10000});
 await page.getByRole('button',{name:'暫停全部'}).click();
 const position=await page.getByTestId('tool-position').textContent();
 await page.screenshot({path:'reports/hammer-prototype-desktop.png',fullPage:true});
 await expect(page.getByTestId('tool-position')).toHaveText(position);
 await page.getByRole('button',{name:'重試本關'}).click();
 await expect(page.getByTestId('marks-count')).toHaveText('停留刀痕：0 處');
 await expect(page.getByTestId('travel')).toHaveText('尚未歸零');
 await page.getByRole('button',{name:'座標歸零'}).click(); await start.click();
 await expect(page.getByRole('heading',{name:'加工完成',exact:true})).toBeVisible({timeout:40000});
 await expect(page.getByTestId('tool-position')).toHaveText('30.00 mm');
 await expect(page.getByTestId('travel')).toHaveText('80.00 mm');
 const first=await page.evaluate(()=>JSON.parse(localStorage.getItem('machine-lab.hammer-prototype.v1')));
 expect(first.profile[100]).toBe(10); expect(first.profile[250]).toBe(12);
 await page.reload();
 await page.getByRole('button',{name:'讀取已儲存工件，接續第二關'}).click();
 await expect(page.getByRole('heading',{name:'第二關：槌柄前端'})).toBeVisible();
 await page.getByRole('button',{name:'座標歸零'}).click(); await start.click();
 await expect(page.getByRole('heading',{name:'加工完成',exact:true})).toBeVisible({timeout:25000});
 const second=await page.evaluate(()=>JSON.parse(localStorage.getItem('machine-lab.hammer-prototype.v1')));
 expect(second.profile[100]).toBe(10); expect(second.profile[250]).toBe(8);
 await page.getByRole('button',{name:'重試本關'}).click();
 await expect(page.getByTestId('tool-position')).toHaveText('135.00 mm');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'reports/hammer-prototype-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});

test('corrupt save and leaving a running lesson are safe',async({page})=>{
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/#/hammer-prototype');
 await page.evaluate(()=>localStorage.setItem('machine-lab.hammer-prototype.v1','broken'));
 await page.reload();
 await expect(page.getByRole('button',{name:'座標歸零'})).toBeEnabled();
 await page.getByRole('button',{name:'觀看本關示範'}).click();
 await page.getByRole('link',{name:'返回關卡選擇',exact:false}).click();
 await expect(page.getByRole('heading',{name:/加工關卡預覽/})).toBeVisible();
 expect(errors).toEqual([]);
});
