import {test,expect} from '@playwright/test';
test('head player milling → actual checkpoint → drilling → M10, Retry/reload and independent saves',async({page})=>{
  test.setTimeout(600000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/#/levels');await page.getByRole('link',{name:'開始／繼續槌頭 Campaign →',exact:true}).click();
  const start=page.getByRole('button',{name:'開始／繼續槌頭操作',exact:true});
  const begin=async()=>{await expect(start).toBeEnabled({timeout:60000});await start.click();await expect(page.getByTestId('head-tip')).not.toContainText('待確認',{timeout:30000});};
  const set=async(x,y,z)=>{for(const [axis,v] of [['X',x],['Y',y],['Z',z]])if(v!==null)await page.getByRole('spinbutton',{name:'槌頭 '+axis+' 目標',exact:true}).fill(String(v));};
  const move=async(x,y,z)=>{await set(x,y,z);await page.getByRole('button',{name:'X/Y/Z 聯動進給',exact:true}).click();};
  const spin=async()=>{await page.getByRole('button',{name:'啟動槌頭主軸',exact:true}).click();await expect(page.getByTestId('head-spindle')).toContainText('運轉中',{timeout:20000});};
  const inspect=async()=>{await page.getByRole('button',{name:'停止槌頭主軸',exact:true}).click();const b=page.getByRole('button',{name:'檢查槌頭尺寸',exact:true});await expect(b).toBeEnabled({timeout:20000});await b.click();};
  const next=async()=>{await page.getByRole('button',{name:'保存槌頭實際工件 → 下一關',exact:true}).click();await begin();};
  const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('machine-lab.campaign.head.v1')));
  await begin();await expect(page.getByTestId('head-bounds')).toContainText('90.000');
  await move(10,10,21);await spin();await move(10,10,18);await move(20,10,18);await inspect();
  await expect(page.getByTestId('head-result')).toContainText('draft');const stage1=(await read()).working;
  expect(stage1.surface.topMm.some(h=>h===18)).toBe(true);await next();await expect(page.getByTestId('head-checkpoint')).toContainText('r1');
  expect((await read()).working).toEqual(stage1);
  await move(25,10,21);await spin();await move(25,10,18);await move(30,10,17);await inspect();
  await page.getByRole('button',{name:'Retry 槌頭本關',exact:true}).click();expect((await read()).working).toEqual(stage1);
  await move(25,10,21);await spin();await move(25,10,18);await move(30,10,17);await inspect();const stage2=(await read()).working;
  await next();await expect(page.getByTestId('head-checkpoint')).toContainText('r2');expect((await read()).working).toEqual(stage2);
  await set(40,10,15);await page.getByRole('button',{name:'停機 X/Y 裝夾定位',exact:true}).click();await spin();
  await page.getByRole('button',{name:'鑽床 Z 進給',exact:true}).click();await inspect();
  const drilled=(await read()).working;expect(drilled.features[0].diameterMm).toBe(8.5);expect(drilled.features[0].depthMm).toBeCloseTo(5,6);
  await next();await set(40,10,17);await page.getByRole('button',{name:'停機 X/Y 裝夾定位',exact:true}).click();await spin();
  await page.getByRole('button',{name:'鑽床 Z 進給',exact:true}).click();await inspect();
  const tapped=(await read()).working;expect(tapped.features[0].thread.designation).toBe('M10');expect(tapped.features[0].thread.sourceHole).toBe(drilled.features[0].id);
  await expect(page.getByTestId('head-result')).toContainText('draft');await page.reload();await begin();expect((await read()).working).toEqual(tapped);
  expect(await page.evaluate(()=>localStorage.getItem('machine-lab.campaign.handle.v1'))).toBeNull();expect(errors).toEqual([]);
});
test('head Demo pause/replay/skip preserves real workpiece and campaign save',async({page})=>{
  test.setTimeout(180000);await page.goto('/#/campaign/head');
  const start=page.getByRole('button',{name:'開始／繼續槌頭操作',exact:true});await expect(start).toBeEnabled({timeout:60000});await start.click();
  const save=()=>page.evaluate(()=>localStorage.getItem('machine-lab.campaign.head.v1'));const initial=await save();
  await page.getByRole('button',{name:'觀看槌頭示範',exact:true}).click();await expect(page.getByTestId('head-demo')).toContainText('playing',{timeout:20000});
  await page.getByRole('button',{name:'暫停示範',exact:true}).click();await expect(page.getByTestId('head-demo')).toContainText('paused');
  await expect(page.getByRole('button',{name:'X/Y/Z 聯動進給',exact:true})).toBeDisabled();expect(await save()).toBe(initial);
  await page.getByRole('button',{name:'重新播放',exact:true}).click();await expect(page.getByTestId('head-demo')).toContainText('playing',{timeout:20000});
  await page.getByRole('button',{name:'跳過示範／返回操作',exact:true}).click();await expect(page.getByTestId('head-demo')).toContainText('finished',{timeout:20000});expect(await save()).toBe(initial);
});
