import {test,expect} from '@playwright/test';

test('Level 1 uses player machining, real setup/cuts, Retry and an isolated free lathe',async({page})=>{
  test.setTimeout(900000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/#/levels');
  await page.evaluate(()=>localStorage.setItem('machine-lab.machining.handle.v1','free-save-sentinel'));
  await page.getByRole('link',{name:'開始 Level 1 →',exact:true}).click();
  await expect(page).toHaveURL(/#\/level\/handle-basic$/);
  await expect(page.getByRole('button',{name:'開始／繼續操作',exact:true})).toBeEnabled({timeout:60000});
  await expect(page.getByTestId('level-step')).toContainText('Step 1');
  await page.getByRole('button',{name:'開始／繼續操作',exact:true}).click();
  await expect(page.getByTestId('cut-length')).toHaveText('300.000');
  await expect(page.getByTestId('level-step')).toContainText('Step 3');
  await expect(page.getByRole('button',{name:'載入槌柄'})).toHaveCount(0);
  await page.getByText('移動到工件座標',{exact:true}).click();
  const move=async(axis,value)=>{
    await page.getByRole('spinbutton',{name:axis+' 工件座標目標 (mm)'}).fill(String(value));
    await page.getByRole('button',{name:'移動 '+axis,exact:true}).click();
  };
  // Zero in air cannot finish a setup step; clear restores the default datum.
  await page.getByRole('button',{name:'X 歸零',exact:true}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 3');
  await page.getByRole('button',{name:'清除工件座標',exact:true}).click();
  await page.getByRole('button',{name:'▶ 啟動主軸'}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 4');
  await move('X',20);await expect(page.getByTestId('level-step')).toContainText('Step 5');
  await page.getByRole('button',{name:'X 歸零',exact:true}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 6');
  await move('X',4);await move('Z',301);await move('X',0);await move('Z',300);
  await expect(page.getByTestId('level-step')).toContainText('Step 7');
  await page.getByRole('button',{name:'Z 歸零',exact:true}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 8');
  console.info('Level 1: mounting, spindle and both contact/zero steps verified');
  await page.getByRole('button',{name:'檢查加工結果',exact:true}).click();
  await expect(page.getByTestId('level-result')).toContainText('未完成');
  await move('X',4);await page.getByRole('combobox',{name:'加工模式',exact:true}).selectOption('facing');
  await move('Z',-1);await move('X',-20);
  await expect(page.getByTestId('cut-length')).toHaveText('299.000');
  await move('X',4);await page.getByRole('combobox',{name:'加工模式',exact:true}).selectOption('turning');
  await move('Z',-100);await move('X',-3.7);await move('Z',-90);
  await expect(page.getByTestId('cut-stock-diameter')).toHaveText('16.300');
  await expect(page.getByTestId('level-step')).toContainText('Step 9');
  await page.getByRole('button',{name:'■ 停止主軸'}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 10');
  await page.getByRole('button',{name:'檢查加工結果',exact:true}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 10');
  await expect(page.getByTestId('level-result')).toContainText('尺寸驗收待確認（draft）');
  await expect(page.getByRole('table',{name:'尺寸驗收結果'}).getByRole('columnheader')).toHaveCount(4);
  const diameter=page.getByTestId('diameter-measurement'),length=page.getByTestId('length-measurement');
  await expect(diameter.locator('td').nth(0)).toContainText('16.3');
  await expect(diameter.locator('td').nth(0)).toContainText('非驗收範圍');
  await expect(diameter.locator('td').nth(1)).toHaveText('—');
  await expect(diameter.locator('td').nth(2)).toHaveText('草案／未評估');
  await expect(length.locator('td').nth(0)).toHaveText('299');
  await expect(length.getByRole('rowheader')).toContainText('總長 240');
  await expect(length.locator('td').nth(1)).toHaveText('59');
  await expect(length.locator('td').nth(2)).toHaveText('未評估');
  await expect(page.getByTestId('measurement-overcut')).toContainText('未評估');
  await page.getByRole('table',{name:'尺寸驗收結果'}).screenshot({path:'test-results/level1-measurements.png'});
  console.info('Level 1: real cutting measured; unknown range/tolerances remain draft, never pass');
  await page.getByRole('button',{name:'保存實際工件 → 下一關',exact:true}).click();
  await expect(page.getByTestId('campaign-save')).toContainText('r1');
  const checkpoint=await page.evaluate(()=>JSON.parse(localStorage.getItem('machine-lab.campaign.handle.v1')).revisions[1].state);
  expect(checkpoint.lengthMm).toBe(299);
  await page.reload();
  await expect(page.getByTestId('campaign-save')).toContainText('r1',{timeout:60000});
  await page.getByRole('button',{name:'Retry',exact:true}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 1');
  await page.getByRole('button',{name:'開始／繼續操作',exact:true}).click();
  await expect(page.getByTestId('cut-length')).toHaveText('299.000');
  await expect(page.getByTestId('cut-stock-diameter')).toHaveText('20.000');
  await expect(page.getByTestId('level-result')).toHaveCount(0);
  await page.getByRole('button',{name:'檢查加工結果',exact:true}).click();
  await expect(page.getByTestId('diameter-measurement').locator('td').nth(0)).toContainText('16.3');
  await expect(page.getByTestId('length-measurement').locator('td').nth(0)).toHaveText('299');
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('machine-lab.campaign.handle.v1')).working)).toEqual(checkpoint);
  expect(await page.evaluate(()=>localStorage.getItem('machine-lab.machining.handle.v1'))).toBe('free-save-sentinel');
  await page.getByRole('link',{name:'前往自由車床',exact:true}).click();
  await expect(page).toHaveURL(/#\/lathe$/);
  await expect(page.getByTestId('level-step')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'建立毛胚 Ø20 × 300 mm'})).toBeEnabled({timeout:60000});
  await page.getByRole('button',{name:'建立毛胚 Ø20 × 300 mm'}).click();
  await expect(page.getByTestId('cut-length')).toHaveText('300.000');
  await page.getByRole('button',{name:'X 歸零',exact:true}).click();
  await expect(page.getByTestId('cut-x-diameter')).toHaveText('0.000');
  await expect(page.getByTestId('level-step')).toHaveCount(0);
  expect(errors).toEqual([]);
});
