import {test,expect} from '@playwright/test';

test('Level 1 flow: roadmap → practice → result → next level, reload, Retry and an isolated free lathe',async({page})=>{
  test.setTimeout(900000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/#/levels');
  await page.evaluate(()=>localStorage.setItem('machine-lab.machining.handle.v1','free-save-sentinel'));
  await page.getByRole('region',{name:'槌柄路線'}).getByRole('link',{name:'開始 →'}).click();
  await expect(page).toHaveURL(/#\/campaign\/handle$/);
  await expect(page.getByRole('button',{name:'開始實作',exact:true})).toBeEnabled({timeout:60000});
  await expect(page.getByTestId('level-step')).toContainText('Step 1');
  await page.getByRole('button',{name:'開始實作',exact:true}).click();
  await expect(page.getByTestId('cut-length')).toHaveText('300.000');
  await expect(page.getByTestId('level-step')).toContainText('Step 3');
  await expect(page.getByRole('button',{name:'載入槌柄'})).toHaveCount(0);
  await page.getByText('移動到工件座標',{exact:true}).click();
  const move=async(axis,value)=>{
    await page.getByRole('spinbutton',{name:axis+' 工件座標目標 (mm)'}).fill(String(value));
    await page.getByRole('button',{name:'移動 '+axis,exact:true}).click();
  };
  // Zero in air cannot finish a setup step; clear restores the default datum.
  await page.getByRole('button',{name:'X 歸零',exact:true}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 3');
  await page.getByRole('button',{name:'清除工件座標',exact:true}).click();
  await page.getByRole('button',{name:'▶ 啟動主軸'}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 4');
  await move('X',20);await expect(page.getByTestId('level-step')).toContainText('Step 5');
  await page.getByRole('button',{name:'X 歸零',exact:true}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 6');
  await move('X',4);await move('Z',301);await move('X',0);await move('Z',300);
  await expect(page.getByTestId('level-step')).toContainText('Step 7');
  await page.getByRole('button',{name:'Z 歸零',exact:true}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 8');
  console.info('Level 1: mounting, spindle and both contact/zero steps verified');
  await page.getByRole('button',{name:'檢查加工結果',exact:true}).click();
  await expect(page.getByTestId('level-result')).toContainText('還沒完成');
  await page.getByRole('button',{name:'回到實作',exact:true}).click();
  await move('X',4);await page.getByRole('combobox',{name:'加工模式',exact:true}).selectOption('facing');
  await move('Z',-1);await move('X',-20);
  await expect(page.getByTestId('cut-length')).toHaveText('299.000');
  await move('X',4);await page.getByRole('combobox',{name:'加工模式',exact:true}).selectOption('turning');
  await move('Z',-100);await move('X',-3.7);await move('Z',-90);
  await expect(page.getByTestId('cut-stock-diameter')).toHaveText('16.300');
  await expect(page.getByTestId('level-step')).toContainText('Step 9');
  await page.getByRole('button',{name:'■ 停止主軸'}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 10');
  await page.getByRole('button',{name:'檢查加工結果',exact:true}).click();
  await expect(page.getByTestId('level-step')).toContainText('Step 10');
  await expect(page.getByTestId('level-result')).toContainText('尺寸公差待老師確認');
  await expect(page.getByRole('table',{name:'尺寸驗收結果'}).getByRole('columnheader')).toHaveCount(5);
  const diameter=page.getByTestId('diameter-measurement'),length=page.getByTestId('length-measurement');
  await expect(diameter.locator('td').nth(0)).toHaveText('—');
  await expect(diameter.locator('td').nth(1)).toContainText('16.3');
  await expect(diameter.locator('td').nth(3)).toHaveText('不評分');
  await expect(length.getByRole('rowheader')).toContainText('總長');
  await expect(length.locator('td').nth(0)).toHaveText('240');
  await expect(length.locator('td').nth(1)).toHaveText('299');
  await expect(length.locator('td').nth(2)).toHaveText('59');
  await expect(length.locator('td').nth(3)).toHaveText('未評估');
  await expect(page.getByTestId('measurement-overcut')).toContainText('未評估');
  await page.getByRole('table',{name:'尺寸驗收結果'}).screenshot({path:'test-results/level1-measurements.png'});
  console.info('Level 1: real cutting measured; unknown range/tolerances remain draft, never pass');
  await page.getByRole('button',{name:'保存實際工件 → 下一關',exact:true}).click();
  await expect(page.getByTestId('campaign-save')).toContainText('第 2 關');
  const checkpoint=await page.evaluate(()=>JSON.parse(localStorage.getItem('machine-lab.campaign.handle.v1')).revisions[1].state);
  expect(checkpoint.lengthMm).toBe(299);
  await page.reload();
  await expect(page.getByTestId('campaign-save')).toContainText('第 2 關',{timeout:60000});
  await expect(page.getByTestId('level-step')).toContainText('Step 1');
  await page.getByRole('button',{name:'開始實作',exact:true}).click();
  await expect(page.getByTestId('cut-length')).toHaveText('299.000');
  await expect(page.getByTestId('cut-stock-diameter')).toHaveText('20.000');
  await expect(page.getByTestId('level-result')).toHaveCount(0);
  await page.getByRole('button',{name:'檢查加工結果',exact:true}).click();
  await expect(page.getByTestId('diameter-measurement').locator('td').nth(1)).toContainText('16.3');
  await expect(page.getByTestId('length-measurement').locator('td').nth(1)).toHaveText('299');
  // Retry returns to this level's checkpoint (the inherited 299 mm stock), never an ideal model.
  await page.getByRole('button',{name:'重來這一關',exact:true}).click();
  await expect(page.getByTestId('cut-length')).toHaveText('299.000');
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('machine-lab.campaign.handle.v1')).working)).toEqual(checkpoint);
  expect(await page.evaluate(()=>localStorage.getItem('machine-lab.machining.handle.v1'))).toBe('free-save-sentinel');
  await page.getByRole('link',{name:'加工教室',exact:true}).click();
  await expect(page).toHaveURL(/#\/lathe$/);
  await expect(page.getByTestId('level-step')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'放上工件 Ø20×300'})).toBeEnabled({timeout:60000});
  await page.getByRole('button',{name:'放上工件 Ø20×300'}).click();
  await expect(page.getByTestId('cut-length')).toHaveText('300.000');
  await page.getByRole('button',{name:'X 歸零',exact:true}).click();
  await expect(page.getByTestId('cut-x-diameter')).toHaveText('0.000');
  await expect(page.getByTestId('level-step')).toHaveCount(0);
  expect(errors).toEqual([]);
});
