import fs from 'node:fs';import {loadSource} from './model-source.mjs';import {meshComponents} from '../todelete/legacy-analysis/src/modelGeometry.js';
const root='public/models/',read=p=>JSON.parse(fs.readFileSync(root+p)),write=(p,d)=>fs.writeFileSync(root+p,JSON.stringify(d,null,2)+'\n');
const l=read('lathe_parts.json');l.removeNodes=['DetailItem_Infomatin_Board','DetailItem_Lamp','Object_193','Object_195','Object_34','Object_36'];
l.axes.x.range[0]=-.14;l.axes.tail.range[0]=-.278;l.axes.quill.range[0]=-.11;
l.parts.startLever.runAngle=.6;l.parts.startLever.pivot[1]=.506273;l.parts.startLever.bidirectional=true;l.parts.startLever.label='主軸正反轉拉桿';
l.additions.push({name:'TailTravelWheel',kind:'handwheel',position:[.81,.65,-.30],axis:[0,0,1],radius:.065,gripSide:-1,parent:'TailstockAssembly'},{name:'LeftSelectorPivot',kind:'cloneLever',position:[-.8534,.7802,.2213],sourcePivot:[-.4395,.7425,.2003],sources:['Object_28','Object_30']});
l.extraWheels=[{id:'tailTravel',node:'TailTravelWheel',axis:[0,0,1],label:'背面尾座位置手輪',drives:'tail',ratio:.018,speed:2.4,generated:true}];
l.actions.push({id:'gearSelector',node:'LeftSelectorPivot',type:'detent',axis:[0,0,1],label:'左側四段拉桿',degrees:[60,90,120,150],homeIndex:1,referenceDegrees:135});
l.manualReview=['已移除燈、圖紙架及其支柱、主軸黃色護蓋。','左側拉桿以右側單桿外型複製，限定 60／90／120／150 度；未虛構變速齒輪機構。','外撥／內撥啟動主軸相反方向；中位停止。','背面新增尾座位置手輪，尾座位置行程 -0.278～0.04；套筒可伸至 -0.11。'];write('lathe_parts.json',l);
const m=read('milling_split_controls.json');m.model='deliver_milling_machine_split/milling_machine_textured.glb';m.neutralMaterials=false;m.additions=[{name:'ZLiftWheel',kind:'handwheel',position:[.43,.40,-.22],axis:[1,0,0],radius:.075,parent:'Knee_Z_Slide'}];m.wheels.push({id:'zLift',node:'ZLiftWheel',axis:[1,0,0],label:'Z 軸升降手輪',drives:'Knee_Z_Slide',ratio:.009,speed:2.4,generated:true});m.groups.push({name:'MillingStartLever',parent:'Head_Assembly',pivot:[.315,1.748,.110],objects:['Head_Part_023']});m.lever={node:'MillingStartLever',axis:[1,0,0],runAngle:.5,duration:.25,label:'銑床啟動握桿'};m.notes=['已從原始 GLB 逐面恢復 UV、法線與貼圖材質，保留 422 個獨立零件。','新增 Z 升降教學手輪，與工作臺升降連動；原合併膝座鑄件保持固定。','Head_Part_023 握桿依使用者要求作主軸啟停，既有機身開關仍可操作。','手輪導程、握桿用途及新增手輪尺寸仍為教學配置。'];write('milling_split_controls.json',m);
const d=read('drill_press_parts.json'),{scene}=await loadSource(new URL('../public/models/drill_press_interactive.glb',import.meta.url));scene.updateMatrixWorld(true);d.geometrySplits=[];d.reparents=[];
for(const [source,ids,name]of [['HeadInternalSupport',[3,4],'TableClampHandle'],['SurfaceDetailsAndLabels',[25],'TableSurfaceDetail']]){const mesh=scene.getObjectByName(source),cs=meshComponents(mesh),vertices=new Set(cs.filter(c=>ids.includes(c.id)).flatMap(c=>c.indices)),g=mesh.geometry,triangles=[];for(let i=0;i<(g.index?.count||g.attributes.position.count);i+=3)if(vertices.has(g.index?g.index.getX(i):i))triangles.push(i/3);d.geometrySplits.push({source,name,triangles,evidence:'Reviewed connected components '+ids.join(',')});d.reparents.push({node:name,parent:'TableAssembly'});}
d.manualReview.push('原誤放於 HeadInternalSupport 的工作臺鎖緊握把及表面細節已拆出，跟隨 TableAssembly 升降。');write('drill_press_parts.json',d);
