/**
 * Tool Catalog & Configurations for Machine System v1.0
 */
export const TOOL_DEFINITIONS = {
  // Face mill Ø58 (5 inserts); cutting length covers the stock height so a single pass can face it.
  head_face_mill: {id:'head_face_mill',name:'面銑刀 Ø58（教學刀具）',type:'milling',compatibleMachines:['milling'],dimensions:{radius:0.029,shankLength:0.035,cuttingLength:0.032}},
  head_end_mill: {id:'head_end_mill',name:'槌頭立銑刀 Ø8（教學刀具）',type:'milling',compatibleMachines:['milling'],dimensions:{radius:0.004,shankLength:0.035,cuttingLength:0.035}},
  head_drill_85: {id:'head_drill_85',name:'Ø8.5 底孔鑽頭',type:'drilling',compatibleMachines:['drill'],dimensions:{radius:0.00425,shankLength:0.025,cuttingLength:0.049}},
  head_tap_m10: {id:'head_tap_m10',name:'M10 絲攻（牙深待確認）',type:'tapping',compatibleMachines:['drill'],dimensions:{radius:0.005,shankLength:0.025,cuttingLength:0.049},designation:'M10',pilotDiameterMm:8.5},
  turning_tool: {
    id: 'turning_tool',
    name: '外徑精車刀 (Indexable Turning Tool)',
    type: 'turning',
    modelPath: '/models/tools/turning-tool.glb',
    compatibleMachines: ['lathe'],
    dimensions: {
      shankLength: 0.165,
      shankWidth: 0.018,
      shankHeight: 0.018,
      insertRadius: 0.0118,
    },
    operations: ['external_turning', 'facing', 'chamfering'],
    description: '標準 95° 鎢鋼外圓車刀，適用於端面車削、外徑粗車與精車。',
  },
  threading_tool: {
    id: 'threading_tool',
    name: '外螺紋車刀 (External Threading Tool)',
    type: 'threading',
    modelPath: '/models/tools/threading-tool.glb',
    compatibleMachines: ['lathe'],
    dimensions: {
      shankLength: 0.165,
      shankWidth: 0.018,
      shankHeight: 0.018,
      threadAngle: 60,
    },
    operations: ['threading'],
    description: '60° 螺紋車刀片，適用於公制與英制標準外螺紋加工。',
  },
  knurling_tool: {
    id: 'knurling_tool',
    name: '雙輪斜紋滾花刀 (Knurling Tool)',
    type: 'knurling',
    modelPath: '/models/tools/knurling-tool.glb',
    compatibleMachines: ['lathe'],
    dimensions: {
      shankLength: 0.14,
      shankWidth: 0.02,
      wheelDiameter: 0.02,
    },
    operations: ['knurling'],
    description: '高碳鋼雙輪網紋滾花刀，用於加工防滑菱形壓花紋路。',
  },
  end_mill: {
    id: 'end_mill',
    name: '四刃立銑刀 (4-Flute End Mill)',
    type: 'milling',
    modelPath: '/models/tools/end-mill.glb',
    compatibleMachines: ['milling'],
    dimensions: {
      radius: 0.008,
      shankLength: 0.035,
      cuttingLength: 0.035,
      flutes: 4,
    },
    operations: ['slotting', 'side_milling', 'contouring'],
    description: '4 刃平頭立銑刀，適用於銑床溝槽銑削、平面側銑與精密輪廓加工。',
  },
  face_mill: {
    id: 'face_mill',
    name: '四刃面銑刀盤 (Indexable Face Mill)',
    type: 'milling',
    modelPath: '/models/tools/face-mill.glb',
    compatibleMachines: ['milling'],
    dimensions: {
      radius: 0.028,
      shankLength: 0.035,
      cuttingLength: 0.035,
      insertCount: 4,
    },
    operations: ['face_milling'],
    description: '大直徑平面銑削刀盤，配備 4 枚可轉位金色鎢鋼刀片，適用於大面積快速平面銑削。',
  },
  drill_bit: {
    id: 'drill_bit',
    name: '直柄麻花鑽頭 (Twist Drill Bit)',
    type: 'drilling',
    modelPath: '/models/tools/drill-bit.glb',
    compatibleMachines: ['drill', 'lathe'],
    dimensions: {
      radius: 0.006,
      shankLength: 0.025,
      cuttingLength: 0.049,
      flutes: 2,
      pointAngle: 118,
    },
    operations: ['drilling', 'center_drilling'],
    description: '118° 標準頂角雙刃直柄麻花鑽頭，用於鑽床或車床尾座鑽孔。',
  },
  caliper: {
    id: 'caliper',
    name: '游標卡尺 (Vernier Caliper)',
    type: 'measuring',
    modelPath: '/models/tools/caliper.glb',
    compatibleMachines: ['lathe', 'milling', 'drill'],
    dimensions: {
      range: [0, 150],
      resolution: 0.02,
    },
    operations: ['measuring'],
    description: '精密外徑、內徑與深度測量量具。',
  },
};
